INSERT INTO dbo.Geography (Country, Capital, Continent)
VALUES ('Afghanistan', 'Kabul', 'Asia'),
('Albania', 'Tirana', 'Europe'),
('Algeria', 'Algeri', 'Africa'),
('Andorra', 'Andorra la Vella', 'Europe'),
('Angola', 'Luanda', 'Africa'),
('Antigua e Barbuda', 'St. John''s', 'North America'),
('Argentina', 'Buenos Aires', 'South America'),
('Armenia', 'Yerevan', 'Asia'),
('Australia', 'Canberra', 'Oceania'),
('Austria', 'Vienna', 'Europe'),
('Azerbaigian', 'Baku', 'Asia'),
('Bahamas', 'Nassau', 'North America'),
('Bahrein', 'Manama', 'Asia'),
('Bangladesh', 'Dhaka', 'Asia'),
('Barbados', 'Bridgetown', 'North America'),
('Bielorussia', 'Minsk', 'Europe'),
('Belgio', 'Bruxelles', 'Europe'),
('Belize', 'Belmopan', 'North America'),
('Benin', 'Porto-Novo', 'Africa'),
('Bhutan', 'Thimphu', 'Asia'),
('Bolivia', 'Sucre', 'South America'),
('Bosnia ed Erzegovina', 'Sarajevo', 'Europe'),
('Botswana', 'Gaborone', 'Africa'),
('Brasile', 'Brasília', 'South America'),
('Brunei', 'Bandar Seri Begawan', 'Asia'),
('Bulgaria', 'Sofia', 'Europe'),
('Burkina Faso', 'Ouagadougou', 'Africa'),
('Burundi', 'Bujumbura', 'Africa'),
('Capo Verde', 'Praia', 'Africa'),
('Cambogia', 'Phnom Penh', 'Asia'),
('Camerun', 'Yaoundé', 'Africa'),
('Canada', 'Ottawa', 'North America'),
('Repubblica Centrafricana', 'Bangui', 'Africa'),
('Chad', 'N''Djamena', 'Africa'),
('Cile', 'Santiago', 'South America'),
('Cina', 'Pechino', 'Asia'),
('Colombia', 'Bogotá', 'South America'),
('Comore', 'Moroni', 'Africa'),
('Congo', 'Kinshasa', 'Africa'),
('Costa Rica', 'San José', 'North America'),
('Croazia', 'Zagabria', 'Europe'),
('Cuba', 'L''Avana', 'North America'),
('Cipro', 'Nicosia', 'Europe'),
('Repubblica Ceca', 'Praga', 'Europe'),
('Danimarca', 'Copenaghen', 'Europe'),
('Gibuti', 'Gibuti', 'Africa'),
('Dominica', 'Roseau', 'North America'),
('Repubblica Dominicana', 'Santo Domingo', 'North America'),
('Ecuador', 'Quito', 'South America'),
('Egitto', 'Il Cairo', 'Africa'),
('El Salvador', 'San Salvador', 'North America'),
('Guinea Equatoriale', 'Malabo', 'Africa'),
('Eritrea', 'Asmara', 'Africa'),
('Estonia', 'Tallinn', 'Europe'),
('Eswatini', 'Mbabane', 'Africa'),
('Etiopia', 'Addis Abeba', 'Africa'),
('Figi', 'Suva', 'Oceania'),
('Finlandia', 'Helsinki', 'Europe'),
('Francia', 'Parigi', 'Europe'),
('Gabon', 'Libreville', 'Africa'),
('Gambia', 'Banjul', 'Africa'),
('Georgia', 'Tbilisi', 'Asia'),
('Germania', 'Berlino', 'Europe'),
('Ghana', 'Accra', 'Africa'),
('Grecia', 'Atene', 'Europe'),
('Grenada', 'St. George''s', 'North America'),
('Guatemala', 'Città del Guatemala', 'North America'),
('Guinea', 'Conakry', 'Africa'),
('Guinea-Bissau', 'Bissau', 'Africa'),
('Guyana', 'Georgetown', 'South America'),
('Haiti', 'Port-au-Prince', 'North America'),
('Honduras', 'Tegucigalpa', 'North America'),
('Ungheria', 'Budapest', 'Europe'),
('Islanda', 'Reykjavik', 'Europe'),
('India', 'Nuova Delhi', 'Asia'),
('Indonesia', 'Giacarta', 'Asia'),
('Iran', 'Teheran', 'Asia'),
('Iraq', 'Baghdad', 'Asia'),
('Irlanda', 'Dublino', 'Europe'),
('Israele', 'Gerusalemme', 'Asia'),
('Italia', 'Roma', 'Europe'),
('Giamaica', 'Kingston', 'North America'),
('Giappone', 'Tokyo', 'Asia'),
('Giordania', 'Amman', 'Asia'),
('Kazakistan', 'Nur-Sultan', 'Asia'),
('Kenya', 'Nairobi', 'Africa'),
('Kiribati', 'Tarawa', 'Oceania'),
('Kuwait', 'Kuwait City', 'Asia'),
('Kirgizistan', 'Bishkek', 'Asia'),
('Laos', 'Vientiane', 'Asia'),
('Lettonia', 'Riga', 'Europe'),
('Libano', 'Beirut', 'Asia'),
('Lesotho', 'Maseru', 'Africa'),
('Liberia', 'Monrovia', 'Africa'),
('Libia', 'Tripoli', 'Africa'),
('Liechtenstein', 'Vaduz', 'Europe'),
('Lituania', 'Vilnius', 'Europe'),
('Lussemburgo', 'Città di Lussemburgo', 'Europe'),
('Madagascar', 'Antananarivo', 'Africa'),
('Malawi', 'Lilongwe', 'Africa'),
('Malesia', 'Kuala Lumpur', 'Asia'),
('Maldives', 'Male', 'Asia'),
('Mali', 'Bamako', 'Africa'),
('Malta', 'La Valletta', 'Europe'),
('Isole Marshall', 'Majuro', 'Oceania'),
('Mauritania', 'Nouakchott', 'Africa'),
('Mauritius', 'Port Louis', 'Africa'),
('Messico', 'Città del Messico', 'North America'),
('Micronesia', 'Palikir', 'Oceania'),
('Moldova', 'Chisinau', 'Europe'),
('Monaco', 'Monaco', 'Europe'),
('Mongolia', 'Ulaanbaatar', 'Asia'),
('Montenegro', 'Podgorica', 'Europe'),
('Marocco', 'Rabat', 'Africa'),
('Mozambico', 'Maputo', 'Africa'),
('Myanmar', 'Naypyidaw', 'Asia'),
('Namibia', 'Windhoek', 'Africa'),
('Nauru', 'Yaren', 'Oceania'),
('Nepal', 'Kathmandu', 'Asia'),
('Paesi Bassi', 'Amsterdam', 'Europe'),
('Nuova Zelanda', 'Wellington', 'Oceania'),
('Nicaragua', 'Managua', 'North America'),
('Niger', 'Niamey', 'Africa'),
('Nigeria', 'Abuja', 'Africa'),
('Corea del Nord', 'Pyongyang', 'Asia'),
('Macedonia del Nord', 'Skopje', 'Europe'),
('Norvegia', 'Oslo', 'Europe'),
('Oman', 'Mascate', 'Asia'),
('Pakistan', 'Islamabad', 'Asia'),
('Palau', 'Ngerulmud', 'Oceania'),
('Panama', 'Città di Panama', 'North America'),
('Papua Nuova Guinea', 'Port Moresby', 'Oceania'),
('Paraguay', 'Asunción', 'South America'),
('Perù', 'Lima', 'South America'),
('Filippine', 'Manila', 'Asia'),
('Polonia', 'Varsavia', 'Europe'),
('Portogallo', 'Lisbona', 'Europe'),
('Qatar', 'Doha', 'Asia'),
('Romania', 'Bucarest', 'Europe'),
('Russia', 'Mosca', 'Europe/Asia'),
('Ruanda', 'Kigali', 'Africa'),
('Saint Kitts e Nevis', 'Basseterre', 'North America'),
('Saint Lucia', 'Castries', 'North America'),
('Saint Vincent e Grenadine', 'Kingstown', 'North America'),
('Samoa', 'Apia', 'Oceania'),
('San Marino', 'San Marino', 'Europe'),
('Sao Tome e Principe', 'São Tomé', 'Africa'),
('Arabia Saudita', 'Riyadh', 'Asia'),
('Senegal', 'Dakar', 'Africa'),
('Serbia', 'Belgrado', 'Europe'),
('Seychelles', 'Victoria', 'Africa'),
('Sierra Leone', 'Freetown', 'Africa'),
('Singapore', 'Singapore', 'Asia'),
('Slovacchia', 'Bratislava', 'Europe'),
('Slovenia', 'Lubiana', 'Europe'),
('Isole Salomone', 'Honiara', 'Oceania'),
('Somalia', 'Mogadiscio', 'Africa'),
('Sudafrica', 'Pretoria', 'Africa'),
('Corea del Sud', 'Seul', 'Asia'),
('Sudan del Sud', 'Juba', 'Africa'),
('Spagna', 'Madrid', 'Europe'),
('Sri Lanka', 'Colombo', 'Asia'),
('Sudan', 'Khartoum', 'Africa'),
('Suriname', 'Paramaribo', 'South America'),
('Svezia', 'Stoccolma', 'Europe'),
('Svizzera', 'Berna', 'Europe'),
('Siria', 'Damasco', 'Asia'),
('Taiwan', 'Taipei', 'Asia'),
('Tagikistan', 'Dushanbe', 'Asia'),
('Tanzania', 'Dodoma', 'Africa'),
('Thailandia', 'Bangkok', 'Asia'),
('Timor Est', 'Dili', 'Asia'),
('Togo', 'Lomé', 'Africa'),
('Tonga', 'Nuku''alofa', 'Oceania'),
('Trinidad e Tobago', 'Port of Spain', 'North America'),
('Tunisia', 'Tunisi', 'Africa'),
('Turchia', 'Ankara', 'Europe/Asia'),
('Turkmenistan', 'Ashgabat', 'Asia'),
('Tuvalu', 'Funafuti', 'Oceania'),
('Uganda', 'Kampala', 'Africa'),
('Ucraina', 'Kyiv', 'Europe'),
('Emirati Arabi Uniti', 'Abu Dhabi', 'Asia'),
('Regno Unito', 'Londra', 'Europe'),
('Stati Uniti', 'Washington, D.C.', 'North America'),
('Uruguay', 'Montevideo', 'South America'),
('Uzbekistan', 'Tashkent', 'Asia'),
('Vanuatu', 'Port Vila', 'Oceania'),
('Città del Vaticano', 'Città del Vaticano', 'Europe'),
('Venezuela', 'Caracas', 'South America'),
('Vietnam', 'Hanoi', 'Asia'),
('Yemen', 'Sanaa', 'Asia'),
('Zambia', 'Lusaka', 'Africa'),
('Zimbabwe', 'Harare', 'Africa');